In [21]:
#import required packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegressionCV


#https://www.kaggle.com/datasets/prasenjitsharma/hearing-test-classification-problem

In [14]:
df = pd.read_csv('hearing_test.csv')
df

       age  physical_score  test_result
0     33.0            40.7            1
1     50.0            37.2            1
2     52.0            24.7            0
3     56.0            31.0            0
4     35.0            42.9            1
...    ...             ...          ...
4995  73.0             3.9            0
4996  57.0            33.9            1
4997  49.0            34.5            1
4998  38.0            46.4            1
4999  48.0            38.5            1

[5000 rows x 3 columns]

In [15]:
df.corr()

                     age  physical_score  test_result
age             1.000000       -0.782146    -0.683171
physical_score -0.782146        1.000000     0.792716
test_result    -0.683171        0.792716     1.000000

In [16]:
df.head()

    age  physical_score  test_result
0  33.0            40.7            1
1  50.0            37.2            1
2  52.0            24.7            0
3  56.0            31.0            0
4  35.0            42.9            1

In [17]:
df.tail()

       age  physical_score  test_result
4995  73.0             3.9            0
4996  57.0            33.9            1
4997  49.0            34.5            1
4998  38.0            46.4            1
4999  48.0            38.5            1

In [18]:
x = df.drop('test_result', axis=1)

In [19]:
y = df['test_result']
y

0       1
1       1
2       0
3       0
4       1
       ..
4995    0
4996    1
4997    1
4998    1
4999    1
Name: test_result, Length: 5000, dtype: int64

In [20]:
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8, random_state=42)

In [ ]:
model = LogisticRegressionCV()
model.fit(x_train,y_train)

In [ ]:
## model evaluation
# get the prediction for x_test
y_pred = model.predict(x_test)
y_pred

In [24]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
cm

array([[321,  63],
       [ 45, 571]])

In [25]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
accuracy

0.892